name: clang-format
on:
  push:

jobs:
  build:
    name: Format code
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup formatter
        run: |
          sudo apt install -y clang-format

      - name: Format code
        run: |
          clang-format -i -style=Google **/*.cpp **/*.h

      - name: Commit and Push
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git config --local user.email "$(git log --format='%ae' HEAD^!)"
            git config --local user.name "$(git log --format='%an' HEAD^!)"
            git add .
            git commit -m "refactor by Github Actions"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          fi
